> NumPy is an extension to the Python programming language, adding support for large, multi-dimensional (mostly numerical) arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays.

In [4]:
# importing required modules
import numpy as np

### Create arrays

In [5]:
# creating arrays from a list
data1 = [11, 22, 33, 44, 55]
arr1 = np.array(data1)
print (data1, len(data1), type(data1), id(data1))
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, 22, 33, 44, 55] 5 <class 'list'> 2272814902464
[11 22 33 44 55] 5 <class 'numpy.ndarray'> 2272814835792 int32


In [20]:
# creating arrays from a list
data1 = [11, 22.0, 33, 44, 55]
arr1 = np.array(data1)
print (data1, len(data1), type(data1), id(data1))
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, 22.0, 33, 44, 55] 5 <class 'list'> 2677659831808
[11. 22. 33. 44. 55.] 5 <class 'numpy.ndarray'> 2677656663024 float64


In [21]:
# creating arrays from a list
data1 = [11, '22', 33, 44, 55]
arr1 = np.array(data1)
print (data1, len(data1), type(data1), id(data1))
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, '22', 33, 44, 55] 5 <class 'list'> 2677659829120
['11' '22' '33' '44' '55'] 5 <class 'numpy.ndarray'> 2677657097200 <U11


In [22]:
# creating arrays from a list
data1 = [11, 22, 33, True,44, False, 55]
arr1 = np.array(data1)
print (data1, len(data1), type(data1), id(data1))
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, 22, 33, True, 44, False, 55] 7 <class 'list'> 2677656176128
[11 22 33  1 44  0 55] 7 <class 'numpy.ndarray'> 2677657097392 int32


In [12]:
# creating arrays from a list
data1 = [11, '22', 33.5, True, 44, False, 55]
arr1 = np.array(data1)
print (data1, len(data1), type(data1), id(data1))
print (arr1, len(arr1), type(arr1), id(arr1))

[11, '22', 33.5, True, 44, False, 55] 7 <class 'list'> 2677656469696
['11' '22' '33.5' 'True' '44' 'False' '55'] 7 <class 'numpy.ndarray'> 2677656607024


In [3]:
var1 = 100
var2 = var1
var3 = 100
print (var1, type(var1), id(var1))
print (var2, type(var2), id(var2))
print (var3, type(var3), id(var3))

100 <class 'int'> 140709502399376
100 <class 'int'> 140709502399376
100 <class 'int'> 140709502399376


In [6]:
var1 = 257
var2 = var1
var3 = 257
print (var1, type(var1), id(var1))
print (var2, type(var2), id(var2))
print (var3, type(var3), id(var3))

257 <class 'int'> 2677656760208
257 <class 'int'> 2677656760208
257 <class 'int'> 2677656759824


In [8]:
# So if the intialization value is ranging from -5 to 256 then ids against the
# variables will remain the same.
var1 = -6
var2 = var1
var3 = -6
print (var1, type(var1), id(var1))
print (var2, type(var2), id(var2))
print (var3, type(var3), id(var3))

-6 <class 'int'> 2677656580464
-6 <class 'int'> 2677656580464
-6 <class 'int'> 2677656580432


In [18]:
# dealing with range and arange
var1 = range(1, 10, 2)
print (var1, type(var1), len(var1))
print (list(var1))
var1 = np.arange(1, 10, 2)
print (var1, type(var1), len(var1))

range(1, 10, 2) <class 'range'> 5
[1, 3, 5, 7, 9]
[1 3 5 7 9] <class 'numpy.ndarray'> 5


In [26]:
# examining arrays
print (arr1.dtype)
print (arr1.ndim)    # returns number of dimensions
print (arr1.shape)   # returns singleton notation of a tuple
print (arr1.size)    # returns count of data items
print (len(arr1))

int32
1
(7,)
7
7


In [27]:
var1 = (7)
print (var1, type(var1))
var1 = (7,)
print (var1, type(var1))

7 <class 'int'>
(7,) <class 'tuple'>


In [30]:
arr2 = np.array([[100, 200, 300, 400, 900], [500, 600, 700, 800, 950]])
print (arr2, type(arr2))
print (arr2.dtype)
print (arr2.ndim)
print (arr2.shape)
print (arr2.size)
print (len(arr2))

[[100 200 300 400 900]
 [500 600 700 800 950]] <class 'numpy.ndarray'>
int32
2
(2, 5)
10
2


In [38]:
# Creating special arrays
print (np.zeros(10))
print (np.zeros(10).astype(int))
print (np.zeros(10, int))
print (np.zeros([4, 2]))
print (np.zeros(8).reshape(4, 2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [44]:
print (np.zeros(10).astype(int).reshape(2, 5))
print (np.zeros(10).reshape(2, 5).astype(int))
print (np.zeros((2, 5)).astype(int))
print (np.zeros([2, 5]).astype(int))

[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [6]:
print (np.ones(10).astype(int).reshape(2, 5))
print (np.ones(10).reshape(2, 5))
print (np.ones(10).reshape(2, 5).astype(int))
print (np.ones((2, 5)).astype(int))
print (np.ones([2, 5]).astype(int))

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
print (np.linspace(0, 1, 5))
print (np.linspace(1, 10, 10))
print (np.linspace(1, 10, 10).astype(int))

[0.   0.25 0.5  0.75 1.  ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  2  3  4  5  6  7  8  9 10]


In [56]:
print (np.logspace(0, 3, 4))
print (np.logspace(0, 3, 4, base = 2))

[   1.   10.  100. 1000.]
[1. 2. 4. 8.]


In [57]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [12]:
# indexing and Slicing
# Left to Right:  0   1   2   3   4   5   6   7
arr1 = np.array([11, 22, 33, 44, 55, 66, 77, 88])
# Right to Left: -8  -7  -6  -5  -4  -3  -2  -1
print (arr1, len(arr1), type(arr1))
print (arr1[4], arr1[6], arr1[-4], arr1[-2])
print (arr1[4:], arr1[-4:], arr1[1:6], arr1[-7:-2])
print (arr1[::2], arr1[1::2], arr1[::-1])

[11 22 33 44 55 66 77 88] 8 <class 'numpy.ndarray'>
55 77 55 77
[55 66 77 88] [55 66 77 88] [22 33 44 55 66] [22 33 44 55 66]
[11 33 55 77] [22 44 66 88] [88 77 66 55 44 33 22 11]


In [13]:
print (arr1[2:6], arr1[-2:-6], arr1[2:-6], arr1[-2:7])

[33 44 55 66] [] [] [77]


In [19]:
print (arr1[2:6], arr1[-8:-5], arr1[3:-1], arr1[-3:7])

[33 44 55 66] [11 22 33] [44 55 66 77] [66 77]


In [24]:
arr2=np.arange(20).reshape(4,5)
print(arr2,type(arr2),arr2.shape)
print(arr2[1:3,2:4])



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] <class 'numpy.ndarray'> (4, 5)
[[ 7  8]
 [12 13]]


In [ ]:
#using boolean arrays


In [25]:
arr1=np.arange(10) *5
print(arr1,type(arr1))

[ 0  5 10 15 20 25 30 35 40 45] <class 'numpy.ndarray'>


In [31]:
names=np.array(['bob','joe','will',"bob"])
print(names,type(names))
print(names =='bob')
print(names =='Bob')
print((names =='shilpi')|(names =="bob"))


['bob' 'joe' 'will' 'bob'] <class 'numpy.ndarray'>
[ True False False  True]
[False False False False]
[ True False False  True]


In [ ]:
#dealing with random numbers

In [32]:
vect1 = np.random.randn(10)
print (vect1)
vect1 = np.random.randint(1, 10)
print (vect1)

[-0.10268002 -0.8847445   0.60204849 -1.12335882  1.11628748 -0.88845234
 -1.14554303 -0.12002298 -0.2544184  -1.11039969]
9


In [33]:
vect1 = np.random.randn(5000)
print (vect1[:5])
print (np.mean(vect1), np.std(vect1))

[ 0.55341636  0.53628209  0.06529786 -0.66542255  0.85547985]
0.03427329251359197 0.9927724207738198
